# Site settings
title: Mitchell Stride's Website
description: A blog about various projects I create.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mitchell Stride
user_description:
user_title: Electrical Engineering Student
email: mitchellcstride@gmail.com



# Google-analytics
google-analytics:
  id: UA-99003026-1

exclude: ['package.json', 'src' , 'node_modules']
